# Generated by Django 5.1.2 on 2024-11-23 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referral', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='referralrelationship',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to=settings.AUTH_USER_MODEL, verbose_name='Invitee'),
        ),
        migrations.AddField(
            model_name='referralrelationship',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL, verbose_name='Inviter'),
        ),
        migrations.AddField(
            model_name='referralrelationship',
            name='refer_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.referralcode', verbose_name='Referral Code'),
        ),
    ]
