# Generated by Django 5.1.2 on 2024-11-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralrelationship',
            name='refer_code',
        ),
    ]
